env:
  node: true

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
